### ISSUE TITLE
Error when trying to download nonexistent lower chamber state legislative districts for Nebrasksa

### ISSUE THREAD

**Issue by ghing** [datadesk/census-map-downloader#23]
When running:

```
censusmapdownloader --data-dir data legislative-lower-carto
```

I get this error:

```
Traceback (most recent call last):
  File "/home/codespace/.local/bin/censusmapdownloader", line 11, in <module>
    load_entry_point('census-map-downloader', 'console_scripts', 'censusmapdownloader')()
  File "/home/codespace/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/codespace/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/codespace/.local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/codespace/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/codespace/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/codespace/.local/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/workspaces/census-map-downloader/census_map_downloader/cli.py", line 97, in legislative_lower_carto
    obj.run()
  File "/workspaces/census-map-downloader/census_map_downloader/base.py", line 167, in run
    self.download()
  File "/workspaces/census-map-downloader/census_map_downloader/base.py", line 183, in download
    runner.run()
  File "/workspaces/census-map-downloader/census_map_downloader/base.py", line 51, in run
    self.download()
  File "/workspaces/census-map-downloader/census_map_downloader/base.py", line 108, in download
    urlretrieve(self.url, self.zip_path)
  File "/usr/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```
when trying to download Nebraska's file, https://www2.census.gov/geo/tiger/GENZ2018/shp/cb_2018_31_sldl_500k.zip to data/raw/cb_2018_31_sldl_500k.zip, which makes sense because [Nebraksa has a unicameral legislature](https://en.wikipedia.org/wiki/Nebraska_Legislature).

**Comment by ghing** [comment]
This is another thing I'll fix after doing more testing on my implementation for #8.

My instinct is to override the constructor for `StateLegislativeDistrictLowerCartoDownloader` (formerly `StateLegislativeDistrictLowerCartoDownloader2018`) and raise a `NotImplementedError` when the state is Nebraska. Then, in `BaseStateListDownloader.download()`, I'll just catch and ignore that error when constructing the downloader for each state. This feels more natural than adding some kind of `get_states()` method in `BaseStateListDownloader` and overriding that in the subclass, but I'm open to feedback
