### ISSUE TITLE
Places data download stops after one state / Shell is not a LinearRing error

### ISSUE THREAD

**Issue by mariepastora** [datadesk/census-map-downloader#25]
Hello,

I've been trying to download all "places" through the cli, but download stops after getting Alabama (FIPS 01). I'm able to download all counties by doing 
`censusmapdownloader counties` and thought `censusmapdownloader places` would work the same. But in the default output raw directory, I only end up with these files:
```
tl_2018_01_place.cpg
tl_2018_01_place.dbf
tl_2018_01_place.prj
tl_2018_01_place.shp
tl_2018_01_place.shp.ea.iso.xml
tl_2018_01_place.shp.iso.xml
tl_2018_01_place.shx
tl_2018_01_place.zip
```
I get dozens of lines of these errors in the console (they also pop up when downloading counties, even though download ends up being successful)

```
Shell is not a LinearRing
Shell is not a LinearRing
Shell is not a LinearRing
Shell is not a LinearRing
Shell is not a LinearRing
Shell is not a LinearRing
Hole is not a LinearRing
Shell is not a LinearRing
Shell is not a LinearRing
Shell is not a LinearRing
Shell is not a LinearRing
Shell is not a LinearRing
Shell is not a LinearRing
Shell is not a LinearRing
Shell is not a LinearRing
Shell is not a LinearRing
Shell is not a LinearRing
Shell is not a LinearRing
Hole is not a LinearRing
Shell is not a LinearRing
IllegalArgumentException: geometries must not contain null elements
```

and then at the end 

```
/Users/mpatino14/.pyenv/versions/3.7.1/lib/python3.7/site-packages/geopandas/geodataframe.py:432: FutureWarning: Assigning CRS to a GeoDataFrame without a geometry column is now deprecated and will not be supported in the future.
  return GeoDataFrame(rows, columns=columns, crs=crs)
Traceback (most recent call last):
  File "/Users/mpatino14/.pyenv/versions/3.7.1/bin/censusmapdownloader", line 8, in <module>
    sys.exit(cmd())
  File "/Users/mpatino14/.pyenv/versions/3.7.1/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mpatino14/.pyenv/versions/3.7.1/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/mpatino14/.pyenv/versions/3.7.1/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mpatino14/.pyenv/versions/3.7.1/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mpatino14/.pyenv/versions/3.7.1/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/mpatino14/.pyenv/versions/3.7.1/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/mpatino14/.pyenv/versions/3.7.1/lib/python3.7/site-packages/census_map_downloader/cli.py", line 37, in places
    obj.run()
  File "/Users/mpatino14/.pyenv/versions/3.7.1/lib/python3.7/site-packages/census_map_downloader/base.py", line 167, in run
    self.download()
  File "/Users/mpatino14/.pyenv/versions/3.7.1/lib/python3.7/site-packages/census_map_downloader/base.py", line 194, in download
    runner.run()
  File "/Users/mpatino14/.pyenv/versions/3.7.1/lib/python3.7/site-packages/census_map_downloader/base.py", line 53, in run
    self.process()
  File "/Users/mpatino14/.pyenv/versions/3.7.1/lib/python3.7/site-packages/census_map_downloader/base.py", line 145, in process
    cleaned.to_file(self.geojson_path, driver="GeoJSON")
  File "/Users/mpatino14/.pyenv/versions/3.7.1/lib/python3.7/site-packages/geopandas/geodataframe.py", line 746, in to_file
    _to_file(self, filename, driver, schema, index, **kwargs)
  File "/Users/mpatino14/.pyenv/versions/3.7.1/lib/python3.7/site-packages/geopandas/io/file.py", line 239, in _to_file
    schema = infer_schema(df)
  File "/Users/mpatino14/.pyenv/versions/3.7.1/lib/python3.7/site-packages/geopandas/io/file.py", line 299, in infer_schema
    geom_types = _geometry_types(df)
  File "/Users/mpatino14/.pyenv/versions/3.7.1/lib/python3.7/site-packages/geopandas/io/file.py", line 316, in _geometry_types
    geom_types_2D = df[~df.geometry.has_z].geometry.geom_type.unique()
  File "/Users/mpatino14/.pyenv/versions/3.7.1/lib/python3.7/site-packages/pandas/core/generic.py", line 5274, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'has_z'
```

Which I suppose points to an error with geopandas, but I'm just not sure what's going on there. Is there a certain version that I should have? Is there a reason why I'm not getting more data back? 

Here are some geopandas related libs of my current env: 
```
Cartopy==0.18.0
categorical-distance==1.9
census==0.8.17
census-map-downloader==0.1.0
click==7.1.2
click-plugins==1.1.1
descartes==1.1.0
Fiona==1.8.18
gast==0.2.2
GDAL==3.1.2
geographiclib==1.50
geojson==2.5.0
geopandas==0.8.1
geoplot==0.4.1
geopy==2.0.0
numpy==1.19.5
pandas==1.0.5
pyepsg==0.4.0
pyesg==0.1.4
pygeos==0.7.1
pyproj==2.6.1.post1
rasterio==1.1.8
```
Thanks so much for making this! And looking forward to hopefully using it :)

**Comment by mariepastora** [comment]
Updated geopandas to 0.9.0, cligj to 0.7.0, Fiona to 1.8.20, pyproj to 3.1.0 and it worked smoothly -- it processes everything correctly. So all good!
